### ISSUE TITLE
Compile problem

### ISSUE THREAD

**Issue by Itsisme** [peterbmarks/radae_decoder#2]
Hai,

Maybe I mis something trying to compile on Ubuntu 22.04.
The required items are all installed however I run into this : 

[ 63%] Building CXX object CMakeFiles/radae_headless.dir/src/audio/audio_stream_pulse.cpp.o
[ 65%] Linking CXX executable tools/radae_headless
[ 75%] Built target radae_headless
Consolidate compiler generated dependencies of target RADAE_Gui
[ 77%] Building CXX object CMakeFiles/RADAE_Gui.dir/src/gui/main.cpp.o
/Downloads/radae_decoder/src/gui/main.cpp: In function 'int main(int, char**)':
/Downloads/radae_decoder/src/gui/main.cpp:1131:47: error: 'G_APPLICATION_DEFAULT_FLAGS' was not declared in this scope; did you mean 'G_APPLICATION_GET_CLASS'?
 1131 |                                               G_APPLICATION_DEFAULT_FLAGS);
      |                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                               G_APPLICATION_GET_CLASS
make[2]: *** [CMakeFiles/RADAE_Gui.dir/build.make:76: CMakeFiles/RADAE_Gui.dir/src/gui/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:377: CMakeFiles/RADAE_Gui.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/11/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 11.4.0-1ubuntu1~22.04.3' --with-bugurl=file:///usr/share/doc/gcc-11/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-11 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --enable-cet --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-11-0odw26/gcc-11-11.4.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-11-0odw26/gcc-11-11.4.0/debian/tmp-gcn/usr --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-serialization=2
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04.3)

Any hint would help :)

Rgds..
